In [16]:
dataset = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]
dataset

[['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
 ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
 ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [4]:
basket = list()
for transaction in dataset:
    for item in transaction: 
        basket.append(item)
print(basket)
print(set(basket))
print(len(set(basket)))

['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt', 'Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt', 'Milk', 'Apple', 'Kidney Beans', 'Eggs', 'Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt', 'Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']
{'Dill', 'Yogurt', 'Onion', 'Nutmeg', 'Unicorn', 'Kidney Beans', 'Ice cream', 'Apple', 'Eggs', 'Corn', 'Milk'}
11


In [18]:
unique_items = set([item for transaction in dataset for item in transaction])
unique_items_len = len(unique_items)
dataset_len = len(dataset)

print(unique_items)
print('unique_items_len: ', unique_items_len)
print('dataset_len: ', dataset_len)

{'Dill', 'Yogurt', 'Onion', 'Nutmeg', 'Unicorn', 'Kidney Beans', 'Ice cream', 'Apple', 'Eggs', 'Corn', 'Milk'}
unique_items_len:  11
dataset_len:  5


In [24]:
import numpy as np

matrix = np.zeros((dataset_len, unique_items_len))
print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [25]:
for row, transaction in enumerate(dataset): 
    #print(row, transaction)
    for item in transaction: 
        index = list(unique_items).index(item)
        matrix[row, index] = 1
    #print(matrix[row])
print(matrix)

[[0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 1.]
 [1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1.]
 [0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1.]
 [0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0.]]


In [29]:
import pandas as pd

basket_matrix = pd.DataFrame(matrix, columns = list(unique_items))
basket_matrix

Dill  Yogurt  Onion  Nutmeg  Unicorn  Kidney Beans  Ice cream  Apple  Eggs  \
0   0.0     1.0    1.0     1.0      0.0           1.0        0.0    0.0   1.0   
1   1.0     1.0    1.0     1.0      0.0           1.0        0.0    0.0   1.0   
2   0.0     0.0    0.0     0.0      0.0           1.0        0.0    1.0   1.0   
3   0.0     1.0    0.0     0.0      1.0           1.0        0.0    0.0   0.0   
4   0.0     0.0    1.0     0.0      0.0           1.0        1.0    0.0   1.0   

   Corn  Milk  
0   0.0   1.0  
1   0.0   0.0  
2   0.0   1.0  
3   1.0   1.0  
4   1.0   0.0

In [50]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori 

one_hot = TransactionEncoder()
one_hot_matrix = one_hot.fit(dataset).transform(dataset)
print(one_hot_matrix, type(one_hot_matrix))

print('\n')
print(one_hot.columns_)

df = pd.DataFrame(one_hot_matrix, columns = one_hot.columns_)
df

[[False False False  True False  True  True  True  True False  True]
 [False False  True  True False  True False  True  True False  True]
 [ True False False  True False  True  True False False False False]
 [False  True False False False  True  True False False  True  True]
 [False  True False  True  True  True False False  True False False]] <class 'numpy.ndarray'>


['Apple', 'Corn', 'Dill', 'Eggs', 'Ice cream', 'Kidney Beans', 'Milk', 'Nutmeg', 'Onion', 'Unicorn', 'Yogurt']


Apple   Corn   Dill   Eggs  Ice cream  Kidney Beans   Milk  Nutmeg  Onion  \
0  False  False  False   True      False          True   True    True   True   
1  False  False   True   True      False          True  False    True   True   
2   True  False  False   True      False          True   True   False  False   
3  False   True  False  False      False          True   True   False  False   
4  False   True  False   True       True          True  False   False   True   

   Unicorn  Yogurt  
0    False    True  
1    False    True  
2    False   False  
3     True    True  
4    False   False

In [52]:
frequent_itemsets = apriori(df, min_support = 0.6, use_colnames = True)
frequent_itemsets

support                     itemsets
0       0.8                       (Eggs)
1       1.0               (Kidney Beans)
2       0.6                       (Milk)
3       0.6                      (Onion)
4       0.6                     (Yogurt)
5       0.8         (Eggs, Kidney Beans)
6       0.6                (Onion, Eggs)
7       0.6         (Kidney Beans, Milk)
8       0.6        (Onion, Kidney Beans)
9       0.6       (Yogurt, Kidney Beans)
10      0.6  (Onion, Eggs, Kidney Beans)

In [55]:
frequent_itemsets_sorted = frequent_itemsets.sort_values('support', ascending = False)
frequent_itemsets_sorted

support                     itemsets
1       1.0               (Kidney Beans)
0       0.8                       (Eggs)
5       0.8         (Eggs, Kidney Beans)
2       0.6                       (Milk)
3       0.6                      (Onion)
4       0.6                     (Yogurt)
6       0.6                (Onion, Eggs)
7       0.6         (Kidney Beans, Milk)
8       0.6        (Onion, Kidney Beans)
9       0.6       (Yogurt, Kidney Beans)
10      0.6  (Onion, Eggs, Kidney Beans)

In [57]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(frequent_itemsets, metric = 'lift', min_threshold = 1.2)
rules

antecedents            consequents  antecedent support  \
0                (Onion)                 (Eggs)                 0.6   
1                 (Eggs)                (Onion)                 0.8   
2  (Onion, Kidney Beans)                 (Eggs)                 0.6   
3   (Eggs, Kidney Beans)                (Onion)                 0.8   
4                (Onion)   (Eggs, Kidney Beans)                 0.6   
5                 (Eggs)  (Onion, Kidney Beans)                 0.8   

   consequent support  support  confidence  lift  leverage  conviction  
0                 0.8      0.6        1.00  1.25      0.12         inf  
1                 0.6      0.6        0.75  1.25      0.12         1.6  
2                 0.8      0.6        1.00  1.25      0.12         inf  
3                 0.6      0.6        0.75  1.25      0.12         1.6  
4                 0.8      0.6        1.00  1.25      0.12         inf  
5                 0.6      0.6        0.75  1.25      0.12         1.6

In [70]:
rules[rules['antecedents'] == {'Onion'}] 

antecedents           consequents  antecedent support  consequent support  \
0     (Onion)                (Eggs)                 0.6                 0.8   
4     (Onion)  (Eggs, Kidney Beans)                 0.6                 0.8   

   support  confidence  lift  leverage  conviction  
0      0.6         1.0  1.25      0.12         inf  
4      0.6         1.0  1.25      0.12         inf

In [69]:
rules[rules['antecedents'] == frozenset(('Onion',))]

antecedents           consequents  antecedent support  consequent support  \
0     (Onion)                (Eggs)                 0.6                 0.8   
4     (Onion)  (Eggs, Kidney Beans)                 0.6                 0.8   

   support  confidence  lift  leverage  conviction  
0      0.6         1.0  1.25      0.12         inf  
4      0.6         1.0  1.25      0.12         inf

In [71]:
rules[rules['antecedents'] == frozenset(['Onion'])]

antecedents           consequents  antecedent support  consequent support  \
0     (Onion)                (Eggs)                 0.6                 0.8   
4     (Onion)  (Eggs, Kidney Beans)                 0.6                 0.8   

   support  confidence  lift  leverage  conviction  
0      0.6         1.0  1.25      0.12         inf  
4      0.6         1.0  1.25      0.12         inf