In [6]:
a = 1
b = 2

In [11]:
def test(c, d):
    test1 = a + c
    test2 = b + d
    return (var1, var2)

In [12]:
var1, var2 = test(3,4)

In [13]:
var1

4

In [14]:
var2

6

In [16]:
from keras.datasets import mnist
from keras.utils import to_categorical

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [21]:
train_images[0].shape

(28, 28)

In [22]:
train_images.shape

(60000, 28, 28)

In [29]:
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [39]:
train_images = train_images.reshape((60000, 28, 28, 1))
print(train_images.shape)
train_images[0]

(60000, 28, 28, 1)


array([[[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],

       [[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]],

       [[  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
      

In [2]:
import numpy as np

a = np.arange(60).reshape(3,4,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [27]:
a.shape

(3, 4, 5)

In [28]:
a.shape[-1]

5

In [3]:
a = np.arange(8).reshape((2,2,2))
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
a = np.random.randint(0, high=2, size=(2,2))
a

array([[0, 0],
       [1, 0]])

In [16]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [19]:
a = [1,2,3,4,5,6,7,8,9,10]
a[4:8]

[5, 6, 7, 8]

In [26]:
b = np.concatenate(np.array(a).reshape(-1,1), axis=0)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
x = np.array(12)
print(x)
print(x.ndim)
print(x.shape)

12
0
()


In [38]:
x = np.arange(12)
print(x) # numpy array
print(x.ndim)
print(x.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
(12,)


In [8]:
a = {1: 'a', 2: 'b', 3: 'c'}

a.get(2)

'b'

In [10]:
a = [100,120,30,60,40,50]
a.sort()
a

[30, 40, 50, 60, 100, 120]

In [12]:
mid = len(a) // 2
print(mid)
if len(a) % 2 == 0:
    print((a[mid] + a[mid - 1]) / 2)
print(a[mid])

3
55.0
60


In [13]:
6 % 2 == 0

True